# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '0efc4720-d43e-4913-8c45-ae90b28f56b6'

  # Web app name
  webAppName: 'SushmithaWeb'

  # Environment name
  environmentName: 'SushmithaWeb'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  steps:
  - task: Maven@4
    displayName: Build Docker image
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: Maven@3
    displayName: Build Docker image
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'spring-boot:build-image'
      publishJUnitResults: false
      jdkVersionOption: '1.8'

  - task: Docker@2
    inputs:
       containerRegistry: 'sushmithaHub'
       repository: 'Sushmitha'
       command: 'buildAndPush'
       Dockerfile: '**/Dockerfile'